WIKIBASE_NAME=grafo.laoficinacultural.org # the name of your wikibase
WIKIBASE_ADDRESS=grafo.laoficinacultural.org # the web address of your wikibase instance (without https://)
QUERY_ADDRESS=grafoq.laoficinacultural.org # the web address of your query service (without https://)
#RECONCILE_ADDRESS="http://localhost:8000"
RECONCILE_ADDRESS="http://grafo.laoficinacultural.org:8000"
