## OpenRefine Reconciliation Service for Wikibase configuration:
# this is the configuration values for the config.sh generator.

export WIKIBASE_NAME=wb.local	# the name of your wikibase
export WIKIBASE_ADDRESS=wb.local # the web address of your wikibase instance (without https://)
export QUERY_ADDRESS=wbqs.local # the web address of your query service (without https://)
export RECONCILE_ADDRESS="http://${WIKIBASE_NAME}:8000" 

# run me like this:
# 	source config.conf
#
# then run the configuration script:
#	bash config.sh
