services:

  openrefine-redis:
    image: "redis:alpine"
    expose:
      - "6379"

  openrefine-endpoint:
    image: registry.gitlab.com/nfdi4culture/openrefine-reconciliation-services/openrefine-wikibase:${OPENREFINE_VERSION}
    ports:
     - "${RECONCILE_PORT}:8000"
    volumes:
     - ./openrefine_conf/config.py:/openrefine-wikibase/config.py
     - ./openrefine_conf/manifest.json:/openrefine-wikibase/static/manifest.json
    depends_on:
     - openrefine-redis
    env_file:
       - ".env"
